package pl.invoice.service.invoice.soap;

public class XmlRequestAndResponse {

  public static final String GET_INVOICE_BY_ID_REQUEST_INVOICE_NOT_FOUND =
      "<inv:getInvoiceByIdRequest xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:id>1</inv:id>\n"
          + "      </inv:getInvoiceByIdRequest>\n";

  public static final String GET_INVOICE_BY_ID_REQUEST =
      "<inv:getInvoiceByIdRequest xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:id>1</inv:id>\n"
          + "      </inv:getInvoiceByIdRequest>\n";

  public static final String GET_INVOICES_WITHIN_DATE_RANGE_REQUEST =
      "<inv:getInvoicesWithinDateRangeRequest xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:fromDate>2017-10-01</inv:fromDate>\n"
          + "         <inv:toDate>2017-11-30</inv:toDate>\n"
          + "      </inv:getInvoicesWithinDateRangeRequest>\n";

  public static final String GET_INVOICE_BY_ID_RESPONSE_INVOICE_NOT_FOUND =
      "<SOAP-ENV:Fault xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">\n"
          + "         <faultcode>SOAP-ENV:Server</faultcode>\n"
          + "         <faultstring xml:lang=\"en\">Invoice with id 1 not found.</faultstring>\n"
          + "      </SOAP-ENV:Fault>\n";

  public static final String ADD_UPDATE_INVOICE_WRONG_DATA_RESPONSE =
      "      <SOAP-ENV:Fault xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">\n"
          + "         <faultcode>SOAP-ENV:Server</faultcode>\n"
          + "         <faultstring xml:lang=\"en\">Incorrect invoice data provided:\n"
          + "[Supplier name not provided.]</faultstring>\n"
          + "      </SOAP-ENV:Fault>\n";

  public static final String GET_INVOICE_BY_ID_RESPONSE =
      "<ns2:getInvoiceByIdResponse \n"
          + " xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "         <ns2:invoice>\n"
          + "            <ns2:id>1</ns2:id>\n"
          + "            <ns2:supplier>\n"
          + "               <ns2:name>Supplier3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>2222</ns2:postalCode>\n"
          + "                  <ns2:city>City2</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>2222222</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL222220</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL987654321</ns2:bankAccount>\n"
          + "            </ns2:supplier>\n"
          + "            <ns2:customer>\n"
          + "               <ns2:name>Customer3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>1111</ns2:postalCode>\n"
          + "                  <ns2:city>City</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>1111111</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL000003</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL123456789</ns2:bankAccount>\n"
          + "            </ns2:customer>\n"
          + "            <ns2:entryList>\n"
          + "               <ns2:invoiceEntry>\n"
          + "                  <ns2:quantity>1.0</ns2:quantity>\n"
          + "                  <ns2:description>Groceries</ns2:description>\n"
          + "                  <ns2:unitPrice>200</ns2:unitPrice>\n"
          + "                  <ns2:vatRate>0.23</ns2:vatRate>\n"
          + "               </ns2:invoiceEntry>\n"
          + "            </ns2:entryList>\n"
          + "            <ns2:issueDate>2017-11-29</ns2:issueDate>\n"
          + "            <ns2:dueDate>2018-01-31</ns2:dueDate>\n"
          + "            <ns2:isPaid>true</ns2:isPaid>\n"
          + "         </ns2:invoice>\n"
          + "      </ns2:getInvoiceByIdResponse>";

  public static final String GET_INVOICE_BY_ID_RESPONSE_AFTER_UPDATE =
      "<ns2:getInvoiceByIdResponse \n"
          + " xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "         <ns2:invoice>\n"
          + "            <ns2:id>1</ns2:id>\n"
          + "            <ns2:supplier>\n"
          + "               <ns2:name>Supplier3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>2222</ns2:postalCode>\n"
          + "                  <ns2:city>City2</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>2222222</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL222220</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL987654321</ns2:bankAccount>\n"
          + "            </ns2:supplier>\n"
          + "            <ns2:customer>\n"
          + "               <ns2:name>Customer3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>1111</ns2:postalCode>\n"
          + "                  <ns2:city>City</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>1111111</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL000003</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL123456789</ns2:bankAccount>\n"
          + "            </ns2:customer>\n"
          + "            <ns2:entryList>\n"
          + "               <ns2:invoiceEntry>\n"
          + "                  <ns2:quantity>1.0</ns2:quantity>\n"
          + "                  <ns2:description>Bread</ns2:description>\n"
          + "                  <ns2:unitPrice>200</ns2:unitPrice>\n"
          + "                  <ns2:vatRate>0.23</ns2:vatRate>\n"
          + "               </ns2:invoiceEntry>\n"
          + "            </ns2:entryList>\n"
          + "            <ns2:issueDate>2017-11-29</ns2:issueDate>\n"
          + "            <ns2:dueDate>2018-01-31</ns2:dueDate>\n"
          + "            <ns2:isPaid>true</ns2:isPaid>\n"
          + "         </ns2:invoice>\n"
          + "      </ns2:getInvoiceByIdResponse>";

  public static final String ADD_FIRST_INVOICE_REQUEST =
      "<inv:addInvoiceRequest \n"
          + " xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:invoice>\n"
          + "            <inv:id>0</inv:id>\n"
          + "            <inv:supplier>\n"
          + "               <inv:name>Supplier3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>2222</inv:postalCode>\n"
          + "                  <inv:city>City2</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>2222222</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL222220</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL987654321</inv:bankAccount>\n"
          + "            </inv:supplier>\n"
          + "            <inv:customer>\n"
          + "               <inv:name>Customer3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>1111</inv:postalCode>\n"
          + "                  <inv:city>City</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>1111111</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL000003</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL123456789</inv:bankAccount>\n"
          + "            </inv:customer>\n"
          + "            <inv:entryList>\n"
          + "               <inv:invoiceEntry>\n"
          + "                  <inv:quantity>1</inv:quantity>\n"
          + "                  <inv:description>Groceries</inv:description>\n"
          + "                  <inv:unitPrice>200</inv:unitPrice>\n"
          + "                  <inv:vatRate>0.23</inv:vatRate>\n"
          + "               </inv:invoiceEntry>\n"
          + "            </inv:entryList>\n"
          + "            <inv:issueDate>2017-11-29</inv:issueDate>\n"
          + "            <inv:dueDate>2018-01-31</inv:dueDate>\n"
          + "            <inv:isPaid>true</inv:isPaid>\n"
          + "         </inv:invoice>\n"
          + "      </inv:addInvoiceRequest>";

  public static final String ADD_INVOICE_WRONG_REQUEST =
      "<inv:addInvoiceRequest \n"
          + " xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:invoice>\n"
          + "            <inv:id>0</inv:id>\n"
          + "            <inv:supplier>\n"
          + "               <inv:name></inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>2222</inv:postalCode>\n"
          + "                  <inv:city>City2</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>2222222</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL222220</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL987654321</inv:bankAccount>\n"
          + "            </inv:supplier>\n"
          + "            <inv:customer>\n"
          + "               <inv:name>Customer3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>1111</inv:postalCode>\n"
          + "                  <inv:city>City</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>1111111</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL000003</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL123456789</inv:bankAccount>\n"
          + "            </inv:customer>\n"
          + "            <inv:entryList>\n"
          + "               <inv:invoiceEntry>\n"
          + "                  <inv:quantity>1</inv:quantity>\n"
          + "                  <inv:description>Groceries</inv:description>\n"
          + "                  <inv:unitPrice>200</inv:unitPrice>\n"
          + "                  <inv:vatRate>0.23</inv:vatRate>\n"
          + "               </inv:invoiceEntry>\n"
          + "            </inv:entryList>\n"
          + "            <inv:issueDate>2017-11-29</inv:issueDate>\n"
          + "            <inv:dueDate>2018-01-31</inv:dueDate>\n"
          + "            <inv:isPaid>true</inv:isPaid>\n"
          + "         </inv:invoice>\n"
          + "      </inv:addInvoiceRequest>";

  public static final String ADD_SECOND_INVOICE_REQUEST =
      "<inv:addInvoiceRequest \n"
          + " xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:invoice>\n"
          + "            <inv:id>0</inv:id>\n"
          + "            <inv:supplier>\n"
          + "               <inv:name>Supplier3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>2222</inv:postalCode>\n"
          + "                  <inv:city>City2</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>2222222</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL222220</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL987654321</inv:bankAccount>\n"
          + "            </inv:supplier>\n"
          + "            <inv:customer>\n"
          + "               <inv:name>Customer3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>1111</inv:postalCode>\n"
          + "                  <inv:city>City</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>1111111</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL000003</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL123456789</inv:bankAccount>\n"
          + "            </inv:customer>\n"
          + "            <inv:entryList>\n"
          + "               <inv:invoiceEntry>\n"
          + "                  <inv:quantity>1</inv:quantity>\n"
          + "                  <inv:description>Groceries</inv:description>\n"
          + "                  <inv:unitPrice>200</inv:unitPrice>\n"
          + "                  <inv:vatRate>0.23</inv:vatRate>\n"
          + "               </inv:invoiceEntry>\n"
          + "            </inv:entryList>\n"
          + "            <inv:issueDate>2017-12-29</inv:issueDate>\n"
          + "            <inv:dueDate>2018-01-31</inv:dueDate>\n"
          + "            <inv:isPaid>true</inv:isPaid>\n"
          + "         </inv:invoice>\n"
          + "      </inv:addInvoiceRequest>";

  public static final String UPDATE_INVOICE_REQUEST =
      "<inv:updateInvoiceRequest \n"
          + " xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:invoice>\n"
          + "            <inv:id>1</inv:id>\n"
          + "            <inv:supplier>\n"
          + "               <inv:name>Supplier3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>2222</inv:postalCode>\n"
          + "                  <inv:city>City2</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>2222222</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL222220</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL987654321</inv:bankAccount>\n"
          + "            </inv:supplier>\n"
          + "            <inv:customer>\n"
          + "               <inv:name>Customer3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>1111</inv:postalCode>\n"
          + "                  <inv:city>City</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>1111111</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL000003</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL123456789</inv:bankAccount>\n"
          + "            </inv:customer>\n"
          + "            <inv:entryList>\n"
          + "               <inv:invoiceEntry>\n"
          + "                  <inv:quantity>1</inv:quantity>\n"
          + "                  <inv:description>Bread</inv:description>\n"
          + "                  <inv:unitPrice>200</inv:unitPrice>\n"
          + "                  <inv:vatRate>0.23</inv:vatRate>\n"
          + "               </inv:invoiceEntry>\n"
          + "            </inv:entryList>\n"
          + "            <inv:issueDate>2017-11-29</inv:issueDate>\n"
          + "            <inv:dueDate>2018-01-31</inv:dueDate>\n"
          + "            <inv:isPaid>true</inv:isPaid>\n"
          + "         </inv:invoice>\n"
          + "      </inv:updateInvoiceRequest>";

  public static final String UPDATE_INVOICE_WRONG_REQUEST =
      "<inv:updateInvoiceRequest \n"
          + " xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:invoice>\n"
          + "            <inv:id>1</inv:id>\n"
          + "            <inv:supplier>\n"
          + "               <inv:name></inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>2222</inv:postalCode>\n"
          + "                  <inv:city>City2</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>2222222</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL222220</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL987654321</inv:bankAccount>\n"
          + "            </inv:supplier>\n"
          + "            <inv:customer>\n"
          + "               <inv:name>Customer3</inv:name>\n"
          + "               <inv:address>\n"
          + "                  <inv:street>Street3</inv:street>\n"
          + "                  <inv:postalCode>1111</inv:postalCode>\n"
          + "                  <inv:city>City</inv:city>\n"
          + "                  <inv:country>PL</inv:country>\n"
          + "               </inv:address>\n"
          + "               <inv:phoneNumber>1111111</inv:phoneNumber>\n"
          + "               <inv:vatIdentificationNumber>PL000003</inv:vatIdentificationNumber>\n"
          + "               <inv:bankAccount>PL123456789</inv:bankAccount>\n"
          + "            </inv:customer>\n"
          + "            <inv:entryList>\n"
          + "               <inv:invoiceEntry>\n"
          + "                  <inv:quantity>1</inv:quantity>\n"
          + "                  <inv:description>Bread</inv:description>\n"
          + "                  <inv:unitPrice>200</inv:unitPrice>\n"
          + "                  <inv:vatRate>0.23</inv:vatRate>\n"
          + "               </inv:invoiceEntry>\n"
          + "            </inv:entryList>\n"
          + "            <inv:issueDate>2017-11-29</inv:issueDate>\n"
          + "            <inv:dueDate>2018-01-31</inv:dueDate>\n"
          + "            <inv:isPaid>true</inv:isPaid>\n"
          + "         </inv:invoice>\n"
          + "      </inv:updateInvoiceRequest>";

  public static final String ADD_INVOICE_RESPONSE =
      "<ns2:addInvoiceResponse xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "         <ns2:id>1</ns2:id>\n"
          + "      </ns2:addInvoiceResponse>";

  public static final String UPDATE_INVOICE_RESPONSE =
      "<ns2:updateInvoiceResponse xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "         <ns2:id>1</ns2:id>\n"
          + "      </ns2:updateInvoiceResponse>";

  public static final String GET_INVOICES_REQUEST =
      "<ns2:getInvoicesRequest xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "      </ns2:getInvoicesRequest>";

  public static final String GET_INVOICES_WITHIN_DATE_RANGE_RESPONSE =
      "<ns2:getInvoicesWithinDateRangeResponse \n"
          + " xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "<ns2:invoiceList>\n"
          + "            <ns2:id>1</ns2:id>\n"
          + "            <ns2:supplier>\n"
          + "               <ns2:name>Supplier3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>2222</ns2:postalCode>\n"
          + "                  <ns2:city>City2</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>2222222</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL222220</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL987654321</ns2:bankAccount>\n"
          + "            </ns2:supplier>\n"
          + "            <ns2:customer>\n"
          + "               <ns2:name>Customer3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>1111</ns2:postalCode>\n"
          + "                  <ns2:city>City</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>1111111</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL000003</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL123456789</ns2:bankAccount>\n"
          + "            </ns2:customer>\n"
          + "            <ns2:entryList>\n"
          + "               <ns2:invoiceEntry>\n"
          + "                  <ns2:quantity>1.0</ns2:quantity>\n"
          + "                  <ns2:description>Groceries</ns2:description>\n"
          + "                  <ns2:unitPrice>200</ns2:unitPrice>\n"
          + "                  <ns2:vatRate>0.23</ns2:vatRate>\n"
          + "               </ns2:invoiceEntry>\n"
          + "            </ns2:entryList>\n"
          + "            <ns2:issueDate>2017-11-29</ns2:issueDate>\n"
          + "            <ns2:dueDate>2018-01-31</ns2:dueDate>\n"
          + "            <ns2:isPaid>true</ns2:isPaid>\n"
          + "         </ns2:invoiceList>\n"
          + "      </ns2:getInvoicesWithinDateRangeResponse>";

  public static final String GET_INVOICES_RESPONSE =
      "<ns2:getInvoicesResponse \n"
          + " xmlns:ns2=\"http://invoice-project.pl/invoices\">\n"
          + "<ns2:invoiceList>\n"
          + "            <ns2:id>1</ns2:id>\n"
          + "            <ns2:supplier>\n"
          + "               <ns2:name>Supplier3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>2222</ns2:postalCode>\n"
          + "                  <ns2:city>City2</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>2222222</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL222220</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL987654321</ns2:bankAccount>\n"
          + "            </ns2:supplier>\n"
          + "            <ns2:customer>\n"
          + "               <ns2:name>Customer3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>1111</ns2:postalCode>\n"
          + "                  <ns2:city>City</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>1111111</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL000003</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL123456789</ns2:bankAccount>\n"
          + "            </ns2:customer>\n"
          + "            <ns2:entryList>\n"
          + "               <ns2:invoiceEntry>\n"
          + "                  <ns2:quantity>1.0</ns2:quantity>\n"
          + "                  <ns2:description>Groceries</ns2:description>\n"
          + "                  <ns2:unitPrice>200</ns2:unitPrice>\n"
          + "                  <ns2:vatRate>0.23</ns2:vatRate>\n"
          + "               </ns2:invoiceEntry>\n"
          + "            </ns2:entryList>\n"
          + "            <ns2:issueDate>2017-11-29</ns2:issueDate>\n"
          + "            <ns2:dueDate>2018-01-31</ns2:dueDate>\n"
          + "            <ns2:isPaid>true</ns2:isPaid>\n"
          + "         </ns2:invoiceList>\n"
          + "         <ns2:invoiceList>\n"
          + "            <ns2:id>2</ns2:id>\n"
          + "            <ns2:supplier>\n"
          + "               <ns2:name>Supplier3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>2222</ns2:postalCode>\n"
          + "                  <ns2:city>City2</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>2222222</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL222220</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL987654321</ns2:bankAccount>\n"
          + "            </ns2:supplier>\n"
          + "            <ns2:customer>\n"
          + "               <ns2:name>Customer3</ns2:name>\n"
          + "               <ns2:address>\n"
          + "                  <ns2:street>Street3</ns2:street>\n"
          + "                  <ns2:postalCode>1111</ns2:postalCode>\n"
          + "                  <ns2:city>City</ns2:city>\n"
          + "                  <ns2:country>PL</ns2:country>\n"
          + "               </ns2:address>\n"
          + "               <ns2:phoneNumber>1111111</ns2:phoneNumber>\n"
          + "               <ns2:vatIdentificationNumber>PL000003</ns2:vatIdentificationNumber>\n"
          + "               <ns2:bankAccount>PL123456789</ns2:bankAccount>\n"
          + "            </ns2:customer>\n"
          + "            <ns2:entryList>\n"
          + "               <ns2:invoiceEntry>\n"
          + "                  <ns2:quantity>1.0</ns2:quantity>\n"
          + "                  <ns2:description>Groceries</ns2:description>\n"
          + "                  <ns2:unitPrice>200</ns2:unitPrice>\n"
          + "                  <ns2:vatRate>0.23</ns2:vatRate>\n"
          + "               </ns2:invoiceEntry>\n"
          + "            </ns2:entryList>\n"
          + "            <ns2:issueDate>2017-12-29</ns2:issueDate>\n"
          + "            <ns2:dueDate>2018-01-31</ns2:dueDate>\n"
          + "            <ns2:isPaid>true</ns2:isPaid>\n"
          + "       </ns2:invoiceList>\n"
          + "      </ns2:getInvoicesResponse>";

  public static final String DELETE_INVOICE_REQUEST =
      "<inv:deleteInvoiceRequest xmlns:inv=\"http://invoice-project.pl/invoices\">\n"
          + "         <inv:id>1</inv:id>\n"
          + "      </inv:deleteInvoiceRequest>\n";
}